### PR TITLE
Add Check by Methods and Remove Check isRunningOnEmulator by default

### PR DESCRIPTION
**Pull request by iPMisterX**
# Remove Check isRunningOnEmulator by default
Methods | Description
 --- | --- 
IRoot.isRooted | Check with rootBeer and with internal checks.
IRoot.isRootedWithBusyBox | Check with rootBeer with BusyBox and with internal checks.
IRoot.isRootedWithEmulator | Check with rootBeer and with internal checks and with **isRunningOnEmulator**
IRoot.isRootedWithBusyBoxWithEmulator | Check with rootBeer with BusyBox and with internal checks and with **isRunningOnEmulator**

## RootBear Library
Methods | Description | Boolean | Boolean
 --- | --- | --- | ---
IRoot.detectRootManagementApps | Root Management Apps | true | false
IRoot.detectPotentiallyDangerousApps | Potentially Dangerous Apps | true | false
IRoot.detectTestKeys | Test Keys | true | false
IRoot.checkForBusyBoxBinary | BusyBox Binary | true | false
IRoot.checkForSuBinary | Su Binary | true | false
IRoot.checkSuExists | Su Exists | true | false
IRoot.checkForRWPaths | RW Paths | true | false
IRoot.checkForDangerousProps | Dangerous Props | true | false
IRoot.checkForRootNative | Root Native | true | false
IRoot.detectRootCloakingApps | Root Cloaking Apps | true | false
IRoot.isSelinuxFlagInEnabled | Selinux Flag Enabled | true | false

## InternalRootDetection
Methods | Description | Boolean | Boolean
 --- | --- | --- | ---
IRoot.isExistBuildTags | Exist Build Tags | true | false
IRoot.doesSuperuserApkExist | Superuser Apk Exist | true | false
IRoot.isExistSUPath | Exist SU Path | true | false
IRoot.checkDirPermissions | Dir Permissions | true | false
IRoot.checkExecutingCommands | Executing Commands | true | false
IRoot.checkInstalledPackages | Installed Packages | true | false
IRoot.checkforOverTheAirCertificates | Over The Air Certificates | true | false
IRoot.isRunningOnEmulator | Running On Emulator | true | false

## isRunningOnEmulator
Methods | Description | Boolean | Boolean
 --- | --- | --- | ---
IRoot.simpleCheckEmulator | Build.MODEL.contains("Emulator") | true | false
IRoot.simpleCheckSDKBF86 | Build.MODEL.contains("Android SDK built for x86")| true | false
IRoot.simpleCheckQRREFPH | Build.BOARD.equals("QC_Reference_Phone") | true | false
IRoot.simpleCheckBuild | Build.HOST.startsWith("Build") | true | false
IRoot.checkGenymotion | Build.MANUFACTURER.contains("Genymotion") | true | false
IRoot.checkGeneric | Build.FINGERPRINT.startsWith("generic") \|\| (Build.BRAND.startsWith("generic") && Build.DEVICE.startsWith("generic")) | true | false
IRoot.checkGoogleSDK | Build.MODEL.contains("google_sdk") \|\| "google_sdk".equals(Build.PRODUCT) | true | false

## getDeviceInfo
Methods | Objects
--- | --- 
IRoot.togetDeviceInfo | info

**Will return Device Info**
- Build.DEVICE
- Build.MODEL
- Build.MANUFACTURER
- Build.BRAND
- Build.BOARD
- Build.HARDWARE
- Build.PRODUCT
- Build.FINGERPRINT
- Build.HOST
- Build.USER
- System.getProperty("os.name")
- System.getProperty("os.version")
- Build.VERSION.INCREMENTAL
- Build.VERSION.RELEASE
- Build.VERSION.SDK_INT
```
{
   "DEVICE":"lavender",
   "MODEL":"Redmi Note 7",
   "MANUFACTURER":"Xiaomi",
   "BRAND":"xiaomi",
   "BOARD":"sdm660",
   "HARDWARE":"qcom",
   "PRODUCT":"lavender",
   "FINGERPRINT":"xiaomi\/lavender\/lavender:10\/QKQ1.190910.002\/V11.0.1.0.QFGMIXM:user\/release-keys",
   "HOST":"c4-miui-ota-bd05.bj",
   "USER":"builder",
   "OSNAME":"Linux",
   "OSVERSION":"4.4.192-perf+",
   "V.INCREMENTAL":"V11.0.1.0.QFGMIXM",
   "V.RELEASE":"10",
   "V.SDK_INT":29
}
```

### CODE REVIEW

**Comment by WuglyakBolgoink** [comment]
@iPMisterX  thank you!

**Comment by mitsoe** [comment]
Hey, when are you planning to release a new version with this fix?

**Comment by WuglyakBolgoink** [comment]
Hallo @mitsoe at this Weekend!

**Comment by mitsoe** [comment]
@WuglyakBolgoink don't want to be too annoying but anything blocking the release?

**Comment by WuglyakBolgoink** [comment]
@mitsoe done!

**Pull request merged**
